### ISSUE TITLE
Fictitious busbar drawing

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-diagram#19]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Some substation dot not have any busbar section. To help cell detection algo, fictitious busbar sections are added (see `Graph.ensureOneBusInConnectedComponent`). Fictitious busbar section are drawn exactly as if it was a real one.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

* **What is the expected behavior?**
We should hide fictitious busbar section so that diagram looks like exactly as it is in the data model. => feeders connected to a fictitious busbar section should be connected to a single point, like if a fictitious busbar section would be just a fictitious node. 

* **What is the motivation / use case for changing the behavior?**
We want to faithfully draw substation diagram.

**Comment by flo-dup** [comment]
Fixed by #381
