### ISSUE TITLE
Animate feeder arrows

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-diagram#237]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Static feeder arrows

* **What is the expected behavior?**
Animated feeder arrows, if corresponding layout parameter enabled (with speed depending on the power flow values?)

* **What is the motivation / use case for changing the behavior?**
Nice looking? SVG. Not completely convinced of result so far (see below), a bit irritating instead.

* **Other information**
Simply adding the following lines to the components.css does the job, but we could go further to have a speed depending on flow values. With a file like the base-voltages.yml to define the 3 (for instance) speeds with min and max values.
```
.sld-arrow-in {
  offset-rotate: 0deg;
  offset-path: path('M 0,-3 0,3 0,-3');
  animation: move 2s linear infinite;}
.sld-arrow-out {
  offset-rotate: 0deg;
  offset-path: path('M 0,3 0,-3 0,3');
  animation: move 2s linear infinite;}
@keyframes move {
  to { 
    offset-distance: 100%;
  }
}
```
The CSS properties needed are still marked as experimental, but work in most browsers, see [browser compatibility sheet](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#browser_compatibility).
 
![animatedArrows](https://user-images.githubusercontent.com/66690739/117458621-c4da1780-af4a-11eb-99c1-fc91f8cdb7a4.gif)
(here in gif, as github doesn't support svg files - result's smoother in svg)

**Comment by So-Fras** [comment]
- It would be better if the arrows did not go back and forth. The move should only be one-way (in the direction of the arrow);
- The user should have the possibility to switch this feature on and off.
