### ISSUE TITLE
General handling of variable length text

### ISSUE THREAD

**Issue by jonenst** [powsybl/powsybl-diagram#49]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Variable length text is handled in an adhoc fashion

* **What is the expected behavior?**
We should define rules to handle text

* **What is the motivation / use case for changing the behavior?**
This will bring several benefits:
- reduce the overlapping of text with other elements
- allow to compute the size and aspect ratio of the image without rendering it
- reduce the size of the image

For example, in the following simple voltage level, the long feeder name causes the image to have a large "unused" white zone, or to clip the name. 
![Capture d’écran de 2019-11-06 11-47-25](https://user-images.githubusercontent.com/89208/68291953-35208800-008b-11ea-919b-f9c1f3bb1489.png)

Note: https://github.com/powsybl/powsybl-incubator/pull/153  is related and tries to handle the specific case of feeder names overlapping. However it doesn't fix the problem of the rightmost feeder name extending out of the image (or forcing the picture to have a bigger width)

Ideas to deal with variable length text are:
- in some places just ignore it, the text is always short
- for longer text, ellipsize it, with variations: ...zz, aaa... , aa..zz , etc
- for longer text where vertical space is available, do line breaking.

This has to be done on a case by case basis.

For example, for hex feeder names, we could ellipsize the middle and center the label around the feeder. This would allow for much tighter bounding boxes:
![Capture d’écran de 2019-11-06 12-01-43](https://user-images.githubusercontent.com/89208/68292946-3652b480-008d-11ea-983f-f6706bac30f7.png)

For the voltage level name, we need to find a strategy too. It could depend on the size of the whole image because the name is written after the image is computed.

**Comment by flo-dup** [comment]
The size of the whole image is now computed and does not consider the size of the text, whose font size could moreover be defined in an external CSS. It assumes that the user put margins big enough to include the text: a right margin big enough to contain the text of the rightmost feeder, up and down margins big enough to contain the text of all feeders is their name is rotated. Nonetheless it could still be of interest to add a parameter, which, if enabled, ellipsizes the names.

**Comment by flo-dup** [comment]
I think this can be closed: as said in previous comment, the font size is defined in CSS, hence at this level we don't know yet the link between string length and size. We're now assuming that defining margins and/or feeder names is the responsibility of the user.
